name: ana
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  flutter_svg: ^2.0.7
  fl_chart: ^1.0.0

  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.0.15

  # Bluetooth
  flutter_blue_plus: ^1.33.5
  permission_handler: ^11.3.0

  cupertino_icons: ^1.0.8

  path_provider: ^2.1.3
  http: ^1.2.2
  csv: ^5.0.2
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/sidebar.png
    - assets/Settings.png
    - assets/Home.png
    - assets/analytics.png
    - assets/lotus_widget.png
    - assets/Clock.png
    - assets/circle_outer.svg
    - assets/circle_middle.svg
    - assets/circle_inner.svg
    - assets/start_text.svg  
  fonts:
    - family: KronaOne
      fonts:
        - asset: assets/fonts/KronaOne-Regular.ttf
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.otf
